const express=require('express'),http=require('http'),crypto=require('crypto'),fs=require('fs'),path=require('path'),helmet=require('helmet'),jwt=require('jsonwebtoken'),Database=require('better-sqlite3');
const {RateLimiterMemory}=require('rate-limiter-flexible');const {Client}=require('ssh2');const {WebSocketServer}=require('ws');
const app=express(),server=http.createServer(app),PORT=Number(process.env.PORT||8080),JWT_SECRET=process.env.JWT_SECRET,MASTER_KEY=Buffer.from(process.env.MASTER_KEY_HEX||'','hex');
if(!JWT_SECRET||MASTER_KEY.length!==32)throw new Error('JWT_SECRET and 32-byte MASTER_KEY_HEX are required');
app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"]}}}));app.use(express.json({limit:'32kb'}));app.use(express.static(path.join(__dirname,'public'),{dotfiles:'deny',maxAge:'1h'}));
const dataDir=path.join(__dirname,'data');fs.mkdirSync(dataDir,{recursive:true,mode:0o700});const db=new Database(path.join(dataDir,'monitor.db'));db.pragma('journal_mode=WAL');db.pragma('foreign_keys=ON');
db.exec(`CREATE TABLE IF NOT EXISTS servers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,hostname TEXT NOT NULL UNIQUE,agent_hash TEXT NOT NULL,ssh_user TEXT,ssh_port INTEGER DEFAULT 22,ssh_key_enc TEXT,ssh_host_fingerprint TEXT,last_seen INTEGER,status TEXT DEFAULT 'unknown',created_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS metrics(id INTEGER PRIMARY KEY AUTOINCREMENT,server_id INTEGER NOT NULL,ts INTEGER NOT NULL,cpu REAL,ram REAL,disk REAL,load1 REAL,rx REAL,tx REAL,uptime INTEGER,services TEXT,FOREIGN KEY(server_id) REFERENCES servers(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,ts INTEGER NOT NULL,actor TEXT NOT NULL,server_id INTEGER,action TEXT NOT NULL,ip TEXT);`);
try{db.exec('ALTER TABLE servers ADD COLUMN ssh_host_fingerprint TEXT')}catch(e){if(!String(e.message).includes('duplicate column'))throw e}
const limiter=new RateLimiterMemory({points:60,duration:60}),loginLimiter=new RateLimiterMemory({points:8,duration:60}),now=()=>Math.floor(Date.now()/1000),sha256=s=>crypto.createHash('sha256').update(s).digest('hex');
function enc(t){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',MASTER_KEY,iv),o=Buffer.concat([c.update(t,'utf8'),c.final()]);return[iv,c.getAuthTag(),o].map(x=>x.toString('base64')).join('.')}
function dec(b){const[a,t,d]=b.split('.').map(x=>Buffer.from(x,'base64')),c=crypto.createDecipheriv('aes-256-gcm',MASTER_KEY,a);c.setAuthTag(t);return Buffer.concat([c.update(d),c.final()]).toString('utf8')}
function audit(a,s,x,ip){db.prepare('INSERT INTO audit(ts,actor,server_id,action,ip)VALUES(?,?,?,?,?)').run(now(),a,s||null,x,ip||'')}
function auth(req,res,next){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'unauthorized'});try{req.user=jwt.verify(h.slice(7),JWT_SECRET,{issuer:'resellnom-monitor'});next()}catch{res.status(401).json({error:'invalid token'})}}
async function throttle(req,res,next){try{await limiter.consume(req.ip);next()}catch{res.status(429).json({error:'rate limited'})}}
app.post('/api/login',async(req,res)=>{try{await loginLimiter.consume(req.ip)}catch{return res.status(429).json({error:'too many attempts'})}const{username,password}=req.body||{};if(!username||!password||username!==process.env.ADMIN_USER||!process.env.ADMIN_PASSWORD_HASH)return res.status(401).json({error:'invalid credentials'});const ok=await require('bcryptjs').compare(password,process.env.ADMIN_PASSWORD_HASH).catch(()=>false);if(!ok)return res.status(401).json({error:'invalid credentials'});const token=jwt.sign({sub:username,role:'admin'},JWT_SECRET,{expiresIn:'30m',issuer:'resellnom-monitor'});audit(username,null,'login',req.ip);res.json({token})});
app.get('/api/servers',auth,throttle,(req,res)=>{const r=db.prepare('SELECT id,name,hostname,ssh_port,last_seen,status,created_at FROM servers ORDER BY name').all();res.json(r.map(x=>({...x,online:!!x.last_seen&&now()-x.last_seen<90})))})
app.get('/api/servers/:id/metrics',auth,throttle,(req,res)=>{const r=db.prepare('SELECT ts,cpu,ram,disk,load1,rx,tx,uptime,services FROM metrics WHERE server_id=? ORDER BY ts DESC LIMIT 120').all(Number(req.params.id));res.json(r.reverse())})
app.post('/api/servers',auth,throttle,(req,res)=>{const{name,hostname,sshUser='root',sshPort=22,sshPrivateKey='',sshHostFingerprint=''}=req.body||{};if(!name||!hostname||!/^([a-zA-Z0-9.-]+|\[[0-9a-fA-F:]+\])$/.test(hostname)||!sshHostFingerprint)return res.status(400).json({error:'name, hostname and SSH host fingerprint are required'});const token=crypto.randomBytes(32).toString('hex');try{const i=db.prepare('INSERT INTO servers(name,hostname,agent_hash,ssh_user,ssh_port,ssh_key_enc,ssh_host_fingerprint,last_seen,status,created_at)VALUES(?,?,?,?,?,?,?,?,?,?)').run(name,hostname,sha256(token),sshUser,Number(sshPort)||22,sshPrivateKey?enc(sshPrivateKey):null,sshHostFingerprint,null,'pending',now());audit(req.user.sub,i.lastInsertRowid,'server_created',req.ip);res.status(201).json({id:i.lastInsertRowid,agentToken:token})}catch{res.status(409).json({error:'server hostname already exists'})}})
app.delete('/api/servers/:id',auth,throttle,(req,res)=>{const id=Number(req.params.id);db.prepare('DELETE FROM servers WHERE id=?').run(id);audit(req.user.sub,id,'server_deleted',req.ip);res.json({ok:true})})
app.post('/agent/heartbeat',(req,res)=>{const token=String(req.headers['x-resellnom-agent']||'');if(token.length<32)return res.status(401).json({error:'unauthorized'});const s=db.prepare('SELECT * FROM servers WHERE agent_hash=?').get(sha256(token));if(!s)return res.status(401).json({error:'unauthorized'});const m=req.body||{},cpu=Number(m.cpu),ram=Number(m.ram),disk=Number(m.disk);if(![cpu,ram,disk].every(Number.isFinite)||cpu<0||cpu>100||ram<0||ram>100||disk<0||disk>100)return res.status(400).json({error:'bad metrics'});db.prepare('INSERT INTO metrics(server_id,ts,cpu,ram,disk,load1,rx,tx,uptime,services)VALUES(?,?,?,?,?,?,?,?,?,?)').run(s.id,now(),cpu,ram,disk,Number(m.load1)||0,Number(m.rx)||0,Number(m.tx)||0,Number(m.uptime)||0,JSON.stringify(m.services||{}));db.prepare('UPDATE servers SET last_seen=?,status=? WHERE id=?').run(now(),cpu>=90||ram>=90||disk>=90?'warning':'online',s.id);res.json({ok:true})})
const wss=new WebSocketServer({server,path:'/ws/terminal'});wss.on('connection',(ws,req)=>{try{const u=new URL(req.url,'http://localhost'),user=jwt.verify(u.searchParams.get('token')||'',JWT_SECRET,{issuer:'resellnom-monitor'}),s=db.prepare('SELECT * FROM servers WHERE id=?').get(Number(u.searchParams.get('server')));if(user.role!=='admin'||!s||!s.ssh_key_enc||!s.ssh_host_fingerprint)return ws.close(1008,'unauthorized');const c=new Client();c.on('ready',()=>c.shell({term:'xterm-256color'},(e,stream)=>{if(e)return ws.close(1011);stream.on('data',d=>ws.send(d));stream.stderr.on('data',d=>ws.send(d));ws.on('message',m=>{if(Buffer.byteLength(m)<=8192)stream.write(m.toString())});ws.on('close',()=>{stream.end();c.end()});audit(user.sub,s.id,'terminal_connect',req.socket.remoteAddress)})).on('error',()=>ws.close(1011,'ssh error'));c.connect({host:s.hostname,port:s.ssh_port||22,username:s.ssh_user||'root',privateKey:dec(s.ssh_key_enc),readyTimeout:10000,hostVerifier:f=>f===s.ssh_host_fingerprint})}catch{ws.close(1008,'unauthorized')}});
setInterval(()=>db.prepare("UPDATE servers SET status='offline' WHERE last_seen IS NOT NULL AND last_seen<?").run(now()-120),30000);server.listen(PORT,'127.0.0.1',()=>console.log(`ResellNom Monitor listening on 127.0.0.1:${PORT}`));
